# https://github.com/svenstaro/proxyboi/blob/fd1b493d2c2a341205d669cbf6bd549c5731df63/.github/workflows/publish.yml

on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, edited]

name: Publish

jobs:
  normal-compile-publish:
    name: Publish
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu, x86_64-apple-darwin, armv7-unknown-linux-gnueabihf]
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: cryptography-learning-backend
            release_name: cryptography-learning-backend-linux-ubuntu-amd64
            use_cross: false
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            artifact_name: cryptography-learning-backend.exe
            release_name: cryptography-learning-backend-windows-amd64.exe
            use_cross: false
          - target: x86_64-apple-darwin
            os: macos-latest
            artifact_name: cryptography-learning-backend
            release_name: cryptography-learning-backend-macos-amd64
            use_cross: false
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-latest
            artifact_name: cryptography-learning-backend
            release_name: cryptography-learning-backend-linux-armv7-gnueabihf
            use_cross: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use_cross }}
          command: test
      - uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use_cross }}
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.release_name }}
          tag: ${{ github.ref }}

  static-compile-publish:
    name: Static Build Publish on Linux
    runs-on: ubuntu-latest
    env: 
      CARGO_TERM_COLOR: always
      BUILD_TARGET: x86_64-unknown-linux-musl
      BINARY_NAME: cryptography-learning-backend-x86_64-linux-unknown-musl
    steps:
      - uses: actions/checkout@v2
      - name: Static build
        uses: zhxiaogg/cargo-static-build@master
        with:
          cmd: cargo build --release
      - uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ env.BUILD_TARGET }}/release/cryptography-learning-backend
          asset_name: ${{ env.BINARY_NAME }}
          tag: ${{ github.ref }}

