# https://github.com/svenstaro/proxyboi/blob/fd1b493d2c2a341205d669cbf6bd549c5731df63/.github/workflows/publish.yml

on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, edited]

name: Publish

jobs:
  normal-compile-publish:
    name: Publish
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: cryptography-learning-backend
            release_name: cryptography-learning-backend-linux-ubuntu-amd64
          - os: windows-latest
            artifact_name: cryptography-learning-backend.exe
            release_name: cryptography-learning-backend-windows-amd64.exe
          - os: macos-latest
            artifact_name: cryptography-learning-backend
            release_name: cryptography-learning-backend-macos-amd64

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.release_name }}
          tag: ${{ github.ref }}

  cross-compile-publish:
    name: Cross compile publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-unknown-linux-gnueabihf
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/cryptography-learning-backend
          asset_name: cryptography-learning-backend-${{ matrix.target }}
          tag: ${{ github.ref }}

  static-compile-publish:
    name: Static build publish on Linux
    runs-on: ubuntu-latest
    env: 
      CARGO_TERM_COLOR: always
      BUILD_TARGET: x86_64-unknown-linux-musl
      BINARY_NAME: cryptography-learning-backend-x86_64-linux-unknown-musl
    steps:
      - uses: actions/checkout@v2
      - name: Static build
        uses: gmiam/rust-musl-action@master
        with:
          args: cargo build --target $BUILD_TARGET --release
      - uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ env.BUILD_TARGET }}/release/cryptography-learning-backend
          asset_name: ${{ env.BINARY_NAME }}
          tag: ${{ github.ref }}

